-- Curated MVP coverage for Cameroon. This file is idempotent and intentionally
-- keeps only reference data; user and marketplace data must never be seeded here.

insert into public.cities (name, slug, region, sort_order)
values
  ('Douala', 'douala', 'Littoral', 1),
  ('Yaoundé', 'yaounde', 'Centre', 2),
  ('Bafoussam', 'bafoussam', 'Ouest', 3),
  ('Bamenda', 'bamenda', 'Nord-Ouest', 4),
  ('Garoua', 'garoua', 'Nord', 5),
  ('Maroua', 'maroua', 'Extrême-Nord', 6),
  ('Ngaoundéré', 'ngaoundere', 'Adamaoua', 7),
  ('Bertoua', 'bertoua', 'Est', 8),
  ('Buea', 'buea', 'Sud-Ouest', 9),
  ('Limbe', 'limbe', 'Sud-Ouest', 10),
  ('Ebolowa', 'ebolowa', 'Sud', 11),
  ('Kumba', 'kumba', 'Sud-Ouest', 12),
  ('Kribi', 'kribi', 'Sud', 13),
  ('Nkongsamba', 'nkongsamba', 'Littoral', 14),
  ('Edéa', 'edea', 'Littoral', 15),
  ('Dschang', 'dschang', 'Ouest', 16),
  ('Foumban', 'foumban', 'Ouest', 17),
  ('Mbouda', 'mbouda', 'Ouest', 18),
  ('Bafang', 'bafang', 'Ouest', 19),
  ('Sangmélima', 'sangmelima', 'Sud', 20),
  ('Mbalmayo', 'mbalmayo', 'Centre', 21),
  ('Obala', 'obala', 'Centre', 22),
  ('Meiganga', 'meiganga', 'Adamaoua', 23),
  ('Batouri', 'batouri', 'Est', 24),
  ('Yokadouma', 'yokadouma', 'Est', 25),
  ('Guider', 'guider', 'Nord', 26),
  ('Kousséri', 'kousseri', 'Extrême-Nord', 27),
  ('Mokolo', 'mokolo', 'Extrême-Nord', 28),
  ('Yagoua', 'yagoua', 'Extrême-Nord', 29),
  ('Mora', 'mora', 'Extrême-Nord', 30),
  ('Kumbo', 'kumbo', 'Nord-Ouest', 31),
  ('Wum', 'wum', 'Nord-Ouest', 32),
  ('Fundong', 'fundong', 'Nord-Ouest', 33),
  ('Mamfe', 'mamfe', 'Sud-Ouest', 34),
  ('Tiko', 'tiko', 'Sud-Ouest', 35),
  ('Mutengene', 'mutengene', 'Sud-Ouest', 36),
  ('Loum', 'loum', 'Littoral', 37)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  sort_order = excluded.sort_order,
  is_active = true;

insert into public.neighborhoods (city_id, name, slug)
select cities.id, seed.name, seed.slug
from (
  values
    ('douala', 'Akwa', 'akwa'),
    ('douala', 'Bali', 'bali'),
    ('douala', 'Bassa', 'bassa'),
    ('douala', 'Bépanda', 'bepanda'),
    ('douala', 'Bonabéri', 'bonaberi'),
    ('douala', 'Bonamoussadi', 'bonamoussadi'),
    ('douala', 'Bonanjo', 'bonanjo'),
    ('douala', 'Bonapriso', 'bonapriso'),
    ('douala', 'Cité SIC', 'cite-sic'),
    ('douala', 'Deido', 'deido'),
    ('douala', 'Denver', 'denver'),
    ('douala', 'Japoma', 'japoma'),
    ('douala', 'Kotto', 'kotto'),
    ('douala', 'Logbessou', 'logbessou'),
    ('douala', 'Logpom', 'logpom'),
    ('douala', 'Makepe', 'makepe'),
    ('douala', 'Mboppi', 'mboppi'),
    ('douala', 'Ndokoti', 'ndokoti'),
    ('douala', 'Ndogbong', 'ndogbong'),
    ('douala', 'Ndogpassi', 'ndogpassi'),
    ('douala', 'New Bell', 'new-bell'),
    ('douala', 'Nyalla', 'nyalla'),
    ('douala', 'PK 8', 'pk-8'),
    ('douala', 'PK 12', 'pk-12'),
    ('douala', 'Village', 'village'),
    ('douala', 'Yassa', 'yassa'),

    ('yaounde', 'Ahala', 'ahala'),
    ('yaounde', 'Bastos', 'bastos'),
    ('yaounde', 'Biyem-Assi', 'biyem-assi'),
    ('yaounde', 'Ekounou', 'ekounou'),
    ('yaounde', 'Emana', 'emana'),
    ('yaounde', 'Essos', 'essos'),
    ('yaounde', 'Etoa-Meki', 'etoa-meki'),
    ('yaounde', 'Etoudi', 'etoudi'),
    ('yaounde', 'Melen', 'melen'),
    ('yaounde', 'Mendong', 'mendong'),
    ('yaounde', 'Messassi', 'messassi'),
    ('yaounde', 'Mvan', 'mvan'),
    ('yaounde', 'Mvog-Ada', 'mvog-ada'),
    ('yaounde', 'Mvog-Mbi', 'mvog-mbi'),
    ('yaounde', 'Ngoa-Ekellé', 'ngoa-ekelle'),
    ('yaounde', 'Nkolbisson', 'nkolbisson'),
    ('yaounde', 'Nkolmesseng', 'nkolmesseng'),
    ('yaounde', 'Nlongkak', 'nlongkak'),
    ('yaounde', 'Nsam', 'nsam'),
    ('yaounde', 'Odza', 'odza'),
    ('yaounde', 'Olembe', 'olembe'),
    ('yaounde', 'Omnisports', 'omnisports'),
    ('yaounde', 'Santa Barbara', 'santa-barbara'),
    ('yaounde', 'Tsinga', 'tsinga'),

    ('bafoussam', 'Banengo', 'banengo'),
    ('bafoussam', 'Djeleng', 'djeleng'),
    ('bafoussam', 'Famla', 'famla'),
    ('bafoussam', 'Kamkop', 'kamkop'),
    ('bafoussam', 'Kouogouo', 'kouogouo'),
    ('bafoussam', 'Ndiangdam', 'ndiangdam'),
    ('bafoussam', 'Tamdja', 'tamdja'),
    ('bafoussam', 'Tougang', 'tougang'),
    ('bafoussam', 'Tyo', 'tyo'),

    ('bamenda', 'Bayelle', 'bayelle'),
    ('bamenda', 'Commercial Avenue', 'commercial-avenue'),
    ('bamenda', 'Foncha Street', 'foncha-street'),
    ('bamenda', 'Ghana Street', 'ghana-street'),
    ('bamenda', 'Mankon', 'mankon'),
    ('bamenda', 'Mile 2', 'mile-2'),
    ('bamenda', 'Mile 3', 'mile-3'),
    ('bamenda', 'Mile 4', 'mile-4'),
    ('bamenda', 'Mulang', 'mulang'),
    ('bamenda', 'Nkwen', 'nkwen'),
    ('bamenda', 'Ntamulung', 'ntamulung'),
    ('bamenda', 'Old Town', 'old-town'),
    ('bamenda', 'Up Station', 'up-station'),

    ('garoua', 'Bibémiré', 'bibemire'),
    ('garoua', 'Djamboutou', 'djamboutou'),
    ('garoua', 'Laindé', 'lainde'),
    ('garoua', 'Ouro Hourso', 'ouro-hourso'),
    ('garoua', 'Plateau', 'plateau'),
    ('garoua', 'Poumpoumré', 'poumpoumre'),
    ('garoua', 'Roumdé Adjia', 'roumde-adjia'),
    ('garoua', 'Yelwa', 'yelwa'),

    ('maroua', 'Baoliwol', 'baoliwol'),
    ('maroua', 'Djarengol', 'djarengol'),
    ('maroua', 'Domayo', 'domayo'),
    ('maroua', 'Doualaré', 'doualare'),
    ('maroua', 'Dougoy', 'dougoy'),
    ('maroua', 'Hardé', 'harde'),
    ('maroua', 'Kakataré', 'kakatare'),
    ('maroua', 'Palar', 'palar'),
    ('maroua', 'Zokok', 'zokok'),

    ('ngaoundere', 'Baladji', 'baladji'),
    ('ngaoundere', 'Bamyanga', 'bamyanga'),
    ('ngaoundere', 'Burkina', 'burkina'),
    ('ngaoundere', 'Joli Soir', 'joli-soir'),
    ('ngaoundere', 'Madagascar', 'madagascar'),
    ('ngaoundere', 'Mbideng', 'mbideng'),
    ('ngaoundere', 'Onaref', 'onaref'),
    ('ngaoundere', 'Sabongari', 'sabongari'),

    ('bertoua', 'Enia', 'enia'),
    ('bertoua', 'Kano', 'kano'),
    ('bertoua', 'Mbanjou', 'mbanjou'),
    ('bertoua', 'Mokolo', 'mokolo'),
    ('bertoua', 'Nkolbikon', 'nkolbikon'),
    ('bertoua', 'Tigaza', 'tigaza'),
    ('bertoua', 'Yadémé', 'yademe'),

    ('buea', 'Bokwango', 'bokwango'),
    ('buea', 'Bomaka', 'bomaka'),
    ('buea', 'Bonduma', 'bonduma'),
    ('buea', 'Buea Town', 'buea-town'),
    ('buea', 'Great Soppo', 'great-soppo'),
    ('buea', 'Mile 16', 'mile-16'),
    ('buea', 'Mile 17', 'mile-17'),
    ('buea', 'Molyko', 'molyko'),
    ('buea', 'Sandpit', 'sandpit'),
    ('buea', 'Small Soppo', 'small-soppo'),

    ('limbe', 'Bota', 'bota'),
    ('limbe', 'Church Street', 'church-street'),
    ('limbe', 'Down Beach', 'down-beach'),
    ('limbe', 'Gardens', 'gardens'),
    ('limbe', 'Mabeta', 'mabeta'),
    ('limbe', 'Mile 2', 'mile-2'),
    ('limbe', 'Mile 4', 'mile-4'),
    ('limbe', 'Mokindi', 'mokindi'),
    ('limbe', 'New Town', 'new-town'),
    ('limbe', 'Ngeme', 'ngeme'),

    ('ebolowa', 'Angalé', 'angale'),
    ('ebolowa', 'Bilon', 'bilon'),
    ('ebolowa', 'Essinguili', 'essinguili'),
    ('ebolowa', 'Mekalat', 'mekalat'),
    ('ebolowa', 'New Bell', 'new-bell'),
    ('ebolowa', 'Nko''ovos', 'nkoovos'),

    ('kumba', 'Buea Road', 'buea-road'),
    ('kumba', 'Fiango', 'fiango'),
    ('kumba', 'Hausa Quarter', 'hausa-quarter'),
    ('kumba', 'Kosala', 'kosala'),
    ('kumba', 'Kumba Town', 'kumba-town'),
    ('kumba', 'Mambanda', 'mambanda'),
    ('kumba', 'Mile One', 'mile-one'),
    ('kumba', 'Three Corners', 'three-corners'),

    ('kribi', 'Afan-Mabé', 'afan-mabe'),
    ('kribi', 'Centre-ville', 'centre-ville'),
    ('kribi', 'Dombè', 'dombe'),
    ('kribi', 'Grand Batanga', 'grand-batanga'),
    ('kribi', 'Mpangou', 'mpangou'),
    ('kribi', 'Mpolongwe', 'mpolongwe'),
    ('kribi', 'Ngoye', 'ngoye'),
    ('kribi', 'Talla', 'talla'),

    ('nkongsamba', 'Eboum', 'eboum'),
    ('nkongsamba', 'Ekangté', 'ekangte'),
    ('nkongsamba', 'Mbaressoumtou', 'mbaressoumtou'),
    ('nkongsamba', 'Poola', 'poola'),
    ('nkongsamba', 'Quartier 1', 'quartier-1'),
    ('nkongsamba', 'Quartier 2', 'quartier-2'),
    ('nkongsamba', 'Quartier 3', 'quartier-3'),

    ('edea', 'Amour', 'amour'),
    ('edea', 'Bonamikengué', 'bonamikengue'),
    ('edea', 'Centre-ville', 'centre-ville'),
    ('edea', 'Ekité', 'ekite'),
    ('edea', 'Ferme Suisse', 'ferme-suisse'),
    ('edea', 'Pongo', 'pongo'),

    ('dschang', 'Centre-ville', 'centre-ville'),
    ('dschang', 'Famla', 'famla'),
    ('dschang', 'Foréké-Dschang', 'foreke-dschang'),
    ('dschang', 'Foto', 'foto'),
    ('dschang', 'Paid Ground', 'paid-ground'),
    ('dschang', 'Tchoualé', 'tchouale'),
    ('dschang', 'Tsinkop', 'tsinkop'),

    ('foumban', 'Centre-ville', 'centre-ville'),
    ('foumban', 'Koundoumbain', 'koundoumbain'),
    ('foumban', 'Kounga', 'kounga'),
    ('foumban', 'Manka', 'manka'),
    ('foumban', 'Njinka', 'njinka'),
    ('foumban', 'Njiyoum', 'njiyoum'),

    ('mbouda', 'Bamessingue', 'bamessingue'),
    ('mbouda', 'Centre-ville', 'centre-ville'),
    ('mbouda', 'Fomessa', 'fomessa'),
    ('mbouda', 'Koplah', 'koplah'),
    ('mbouda', 'Tséla', 'tsela'),

    ('bafang', 'Baboutcha', 'baboutcha'),
    ('bafang', 'Centre-ville', 'centre-ville'),
    ('bafang', 'Djeufa', 'djeufa'),
    ('bafang', 'Famkeu', 'famkeu'),
    ('bafang', 'Ngueunack', 'ngueunack'),

    ('sangmelima', 'Akon', 'akon'),
    ('sangmelima', 'Centre-ville', 'centre-ville'),
    ('sangmelima', 'Monavebe', 'monavebe'),
    ('sangmelima', 'Nkol-Ekong', 'nkol-ekong'),
    ('sangmelima', 'Nkoumadjap', 'nkoumadjap'),

    ('mbalmayo', 'Centre-ville', 'centre-ville'),
    ('mbalmayo', 'Minkama', 'minkama'),
    ('mbalmayo', 'New Town', 'new-town'),
    ('mbalmayo', 'Nkolnyama', 'nkolnyama'),
    ('mbalmayo', 'Oyack', 'oyack'),

    ('obala', 'Centre-ville', 'centre-ville'),
    ('obala', 'Elig-Bé', 'elig-be'),
    ('obala', 'Minkama', 'minkama'),
    ('obala', 'Nkolbogo', 'nkolbogo'),
    ('obala', 'Nkometou', 'nkometou'),

    ('meiganga', 'Centre administratif', 'centre-administratif'),
    ('meiganga', 'Haoussa', 'haoussa'),
    ('meiganga', 'Joli Soir', 'joli-soir'),
    ('meiganga', 'Nandéké', 'nandeke'),
    ('meiganga', 'Sabongari', 'sabongari'),

    ('batouri', 'Bazzama', 'bazzama'),
    ('batouri', 'Centre-ville', 'centre-ville'),
    ('batouri', 'Mokolo', 'mokolo'),
    ('batouri', 'Nkolbomo', 'nkolbomo'),
    ('batouri', 'Tigaza', 'tigaza'),

    ('yokadouma', 'Bangué', 'bangue'),
    ('yokadouma', 'Centre-ville', 'centre-ville'),
    ('yokadouma', 'Madjoué', 'madjoue'),
    ('yokadouma', 'Mboy', 'mboy'),
    ('yokadouma', 'Mendoung', 'mendoung'),

    ('guider', 'Baila', 'baila'),
    ('guider', 'Centre-ville', 'centre-ville'),
    ('guider', 'Dourbeye', 'dourbeye'),
    ('guider', 'Larbak', 'larbak'),
    ('guider', 'Ouro-Kessoum', 'ouro-kessoum'),

    ('kousseri', 'Ardébé', 'ardebe'),
    ('kousseri', 'Centre-ville', 'centre-ville'),
    ('kousseri', 'Goz-Attelé', 'goz-attele'),
    ('kousseri', 'Kassalafam', 'kassalafam'),
    ('kousseri', 'Madana', 'madana'),
    ('kousseri', 'Mairie', 'mairie'),

    ('mokolo', 'Centre-ville', 'centre-ville'),
    ('mokolo', 'Gawar', 'gawar'),
    ('mokolo', 'Matakam', 'matakam'),
    ('mokolo', 'Mokong', 'mokong'),
    ('mokolo', 'Ziling', 'ziling'),

    ('yagoua', 'Bongor Road', 'bongor-road'),
    ('yagoua', 'Centre-ville', 'centre-ville'),
    ('yagoua', 'Doukoula', 'doukoula'),
    ('yagoua', 'Kaskao', 'kaskao'),
    ('yagoua', 'Vélé', 'vele'),

    ('mora', 'Centre-ville', 'centre-ville'),
    ('mora', 'Doulo', 'doulo'),
    ('mora', 'Kourgui', 'kourgui'),
    ('mora', 'Mémé', 'meme'),
    ('mora', 'Podoko', 'podoko'),

    ('kumbo', 'Bamkikai', 'bamkikai'),
    ('kumbo', 'Kumbo Town', 'kumbo-town'),
    ('kumbo', 'Mbuluf', 'mbuluf'),
    ('kumbo', 'Meluf', 'meluf'),
    ('kumbo', 'Squares', 'squares'),
    ('kumbo', 'Tobin', 'tobin'),

    ('wum', 'Bu Road', 'bu-road'),
    ('wum', 'Centre-ville', 'centre-ville'),
    ('wum', 'Naikom', 'naikom'),
    ('wum', 'Waindo', 'waindo'),
    ('wum', 'Wum Town', 'wum-town'),

    ('fundong', 'Abuh', 'abuh'),
    ('fundong', 'Fundong Centre', 'fundong-centre'),
    ('fundong', 'Kom', 'kom'),
    ('fundong', 'Njinikom', 'njinikom'),
    ('fundong', 'Tooy', 'tooy'),

    ('mamfe', 'Besongabang', 'besongabang'),
    ('mamfe', 'Egbekaw', 'egbekaw'),
    ('mamfe', 'Mamfe Town', 'mamfe-town'),
    ('mamfe', 'Mile 1', 'mile-1'),
    ('mamfe', 'Small Mamfe', 'small-mamfe'),

    ('tiko', 'Likomba', 'likomba'),
    ('tiko', 'Long Street', 'long-street'),
    ('tiko', 'Mutengene Road', 'mutengene-road'),
    ('tiko', 'New Quarter', 'new-quarter'),
    ('tiko', 'Tiko Town', 'tiko-town'),

    ('mutengene', 'Check Point', 'check-point'),
    ('mutengene', 'Mile 14', 'mile-14'),
    ('mutengene', 'Mile 15', 'mile-15'),
    ('mutengene', 'Mile 16', 'mile-16'),
    ('mutengene', 'Mutengene Town', 'mutengene-town'),

    ('loum', 'Bonkeng', 'bonkeng'),
    ('loum', 'Loum Centre', 'loum-centre'),
    ('loum', 'Loum Chantier', 'loum-chantier'),
    ('loum', 'Manengwassa', 'manengwassa'),
    ('loum', 'Ngodi', 'ngodi')
) as seed(city_slug, name, slug)
join public.cities on cities.slug = seed.city_slug
on conflict (city_id, slug) do update set
  name = excluded.name,
  is_active = true;
