create table public.cities (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(trim(name)) between 2 and 80),
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  region text not null check (region in (
    'Adamaoua',
    'Centre',
    'Est',
    'Extrême-Nord',
    'Littoral',
    'Nord',
    'Nord-Ouest',
    'Ouest',
    'Sud',
    'Sud-Ouest'
  )),
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table public.neighborhoods (
  id bigint generated by default as identity primary key,
  city_id bigint not null references public.cities (id) on delete cascade,
  name text not null check (char_length(trim(name)) between 2 and 100),
  slug text not null check (slug ~ '^[a-z0-9-]+$'),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  unique (city_id, slug),
  unique (id, city_id)
);

create index neighborhoods_city_id_name_idx
on public.neighborhoods (city_id, name);

alter table public.cities enable row level security;
alter table public.neighborhoods enable row level security;

revoke all on table public.cities from anon, authenticated;
revoke all on table public.neighborhoods from anon, authenticated;
grant select on table public.cities to anon, authenticated;
grant select on table public.neighborhoods to anon, authenticated;

create policy "Public can read active cities"
on public.cities
for select
to anon, authenticated
using (is_active);

create policy "Public can read active neighborhoods"
on public.neighborhoods
for select
to anon, authenticated
using (
  is_active
  and exists (
    select 1
    from public.cities
    where cities.id = neighborhoods.city_id
      and cities.is_active
  )
);

alter table public.profiles
  add column city_id bigint references public.cities (id) on delete restrict,
  add column neighborhood_id bigint,
  add column custom_city text check (
    custom_city is null or char_length(trim(custom_city)) between 2 and 80
  ),
  add column custom_neighborhood text check (
    custom_neighborhood is null or char_length(trim(custom_neighborhood)) between 2 and 100
  ),
  add constraint profiles_neighborhood_belongs_to_city_fk
    foreign key (neighborhood_id, city_id)
    references public.neighborhoods (id, city_id)
    on delete restrict;

create index profiles_city_id_idx on public.profiles (city_id);
create index profiles_neighborhood_id_idx on public.profiles (neighborhood_id);

create function public.resolve_profile_location()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  resolved_city text;
  resolved_neighborhood text;
begin
  if new.city_id is not null then
    select name into resolved_city
    from public.cities
    where id = new.city_id and is_active;

    if resolved_city is null then
      raise exception 'Selected city is unavailable';
    end if;

    new.city := resolved_city;
    new.custom_city := null;
  else
    new.custom_city := nullif(trim(coalesce(new.custom_city, new.city)), '');
    new.city := new.custom_city;
  end if;

  if new.neighborhood_id is not null then
    select name into resolved_neighborhood
    from public.neighborhoods
    where id = new.neighborhood_id
      and city_id = new.city_id
      and is_active;

    if resolved_neighborhood is null then
      raise exception 'Selected neighborhood is unavailable for this city';
    end if;

    new.neighborhood := resolved_neighborhood;
    new.custom_neighborhood := null;
  else
    new.custom_neighborhood := nullif(trim(coalesce(new.custom_neighborhood, new.neighborhood)), '');
    new.neighborhood := new.custom_neighborhood;
  end if;

  if new.onboarding_completed and (
    new.display_name is null
    or new.city is null
    or new.neighborhood is null
  ) then
    raise exception 'Name, city and neighborhood are required to complete onboarding';
  end if;

  return new;
end;
$$;

create trigger profiles_resolve_location
before insert or update
on public.profiles
for each row execute function public.resolve_profile_location();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  metadata jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  metadata_city_id bigint;
  metadata_neighborhood_id bigint;
  metadata_name text;
  metadata_custom_city text;
  metadata_custom_neighborhood text;
  has_complete_profile boolean;
begin
  metadata_name := nullif(trim(coalesce(
    metadata ->> 'display_name',
    metadata ->> 'full_name',
    metadata ->> 'name'
  )), '');

  if coalesce(metadata ->> 'city_id', '') ~ '^[0-9]+$' then
    metadata_city_id := (metadata ->> 'city_id')::bigint;
  end if;

  if coalesce(metadata ->> 'neighborhood_id', '') ~ '^[0-9]+$' then
    metadata_neighborhood_id := (metadata ->> 'neighborhood_id')::bigint;
  end if;

  metadata_custom_city := nullif(trim(metadata ->> 'custom_city'), '');
  metadata_custom_neighborhood := nullif(trim(metadata ->> 'custom_neighborhood'), '');

  has_complete_profile := metadata_name is not null
    and (metadata_city_id is not null or metadata_custom_city is not null)
    and (metadata_neighborhood_id is not null or metadata_custom_neighborhood is not null);

  insert into public.profiles (
    id,
    display_name,
    city_id,
    neighborhood_id,
    custom_city,
    custom_neighborhood,
    preferred_language,
    onboarding_completed
  )
  values (
    new.id,
    metadata_name,
    metadata_city_id,
    metadata_neighborhood_id,
    metadata_custom_city,
    metadata_custom_neighborhood,
    case when metadata ->> 'preferred_language' = 'en' then 'en'::public.app_language else 'fr'::public.app_language end,
    has_complete_profile
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

comment on table public.cities is 'Curated Cameroon cities available during registration and profile editing.';
comment on table public.neighborhoods is 'Curated neighborhoods scoped to a Cameroon city.';
comment on column public.profiles.custom_city is 'Fallback city entered when the curated list does not contain the user location.';
comment on column public.profiles.custom_neighborhood is 'Fallback neighborhood entered when the curated list does not contain the user location.';
