create type public.listing_condition as enum ('new', 'like_new', 'good', 'fair');
create type public.listing_status as enum ('draft', 'published', 'reserved', 'sold', 'archived');

create table public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  label_fr text not null check (char_length(trim(label_fr)) between 2 and 50),
  label_en text not null check (char_length(trim(label_en)) between 2 and 50),
  symbol text not null check (char_length(trim(symbol)) between 1 and 60),
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table public.listings (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.profiles (id) on delete cascade,
  category_id bigint not null references public.categories (id) on delete restrict,
  title text not null check (char_length(trim(title)) between 3 and 100),
  description text not null check (char_length(trim(description)) between 20 and 2000),
  price bigint not null check (price between 100 and 1000000000),
  condition public.listing_condition not null,
  status public.listing_status not null default 'draft',
  city_id bigint references public.cities (id) on delete restrict,
  neighborhood_id bigint,
  custom_city text check (custom_city is null or char_length(trim(custom_city)) between 2 and 80),
  custom_neighborhood text check (custom_neighborhood is null or char_length(trim(custom_neighborhood)) between 2 and 100),
  city text not null check (char_length(trim(city)) between 2 and 80),
  neighborhood text not null check (char_length(trim(neighborhood)) between 2 and 100),
  search_vector tsvector generated always as (
    to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, ''))
  ) stored,
  published_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint listings_neighborhood_belongs_to_city_fk
    foreign key (neighborhood_id, city_id)
    references public.neighborhoods (id, city_id)
    on delete restrict
);

create table public.listing_images (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings (id) on delete cascade,
  storage_path text not null unique check (char_length(storage_path) between 20 and 500),
  position smallint not null check (position between 0 and 7),
  width integer check (width is null or width between 1 and 20000),
  height integer check (height is null or height between 1 and 20000),
  created_at timestamptz not null default timezone('utc', now()),
  unique (listing_id, position)
);

create table public.favorites (
  user_id uuid not null references public.profiles (id) on delete cascade,
  listing_id uuid not null references public.listings (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, listing_id)
);

create index listings_feed_idx
on public.listings (status, published_at desc, id);

create index listings_seller_idx
on public.listings (seller_id, created_at desc);

create index listings_category_idx
on public.listings (category_id, status, published_at desc);

create index listings_city_idx
on public.listings (city, status, published_at desc);

create index listings_price_idx
on public.listings (price)
where status = 'published';

create index listings_search_idx
on public.listings using gin (search_vector);

create index listing_images_listing_idx
on public.listing_images (listing_id, position);

create index favorites_listing_idx
on public.favorites (listing_id);

create function public.resolve_listing_location_and_publication()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  resolved_city text;
  resolved_neighborhood text;
begin
  new.title := trim(new.title);
  new.description := trim(new.description);

  if new.city_id is not null then
    select name into resolved_city
    from public.cities
    where id = new.city_id and is_active;

    if resolved_city is null then
      raise exception 'Selected city is unavailable';
    end if;

    new.city := resolved_city;
    new.custom_city := null;
  else
    new.custom_city := nullif(trim(coalesce(new.custom_city, new.city)), '');
    new.city := new.custom_city;
  end if;

  if new.neighborhood_id is not null then
    select name into resolved_neighborhood
    from public.neighborhoods
    where id = new.neighborhood_id
      and city_id = new.city_id
      and is_active;

    if resolved_neighborhood is null then
      raise exception 'Selected neighborhood is unavailable for this city';
    end if;

    new.neighborhood := resolved_neighborhood;
    new.custom_neighborhood := null;
  else
    new.custom_neighborhood := nullif(trim(coalesce(new.custom_neighborhood, new.neighborhood)), '');
    new.neighborhood := new.custom_neighborhood;
  end if;

  if new.city is null or new.neighborhood is null then
    raise exception 'City and neighborhood are required';
  end if;

  if new.status = 'published' and (
    tg_op = 'INSERT'
    or old.status is distinct from 'published'
  ) then
    if not exists (
      select 1 from public.listing_images where listing_id = new.id
    ) then
      raise exception 'At least one image is required to publish a listing';
    end if;
    new.published_at := timezone('utc', now());
  end if;

  return new;
end;
$$;

create trigger listings_resolve_location_and_publication
before insert or update on public.listings
for each row execute function public.resolve_listing_location_and_publication();

create trigger listings_set_updated_at
before update on public.listings
for each row execute function public.set_updated_at();

alter table public.categories enable row level security;
alter table public.listings enable row level security;
alter table public.listing_images enable row level security;
alter table public.favorites enable row level security;

revoke all on table public.categories from anon, authenticated;
revoke all on table public.listings from anon, authenticated;
revoke all on table public.listing_images from anon, authenticated;
revoke all on table public.favorites from anon, authenticated;

grant select on table public.categories to anon, authenticated;
grant select on table public.listings to anon, authenticated;
grant insert, update, delete on table public.listings to authenticated;
grant select on table public.listing_images to anon, authenticated;
grant insert, update, delete on table public.listing_images to authenticated;
grant select, insert, delete on table public.favorites to authenticated;
grant usage on type public.listing_condition to anon, authenticated;
grant usage on type public.listing_status to anon, authenticated;

grant select on table public.profiles to anon;

create policy "Public can read active categories"
on public.categories for select to anon, authenticated
using (is_active);

create policy "Public can read published listings"
on public.listings for select to anon, authenticated
using (status in ('published', 'reserved', 'sold'));

create policy "Sellers can read their own listings"
on public.listings for select to authenticated
using ((select auth.uid()) = seller_id);

create policy "Verified profiles can create their own listings"
on public.listings for insert to authenticated
with check (
  (select auth.uid()) = seller_id
  and exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.onboarding_completed
  )
);

create policy "Sellers can update their own listings"
on public.listings for update to authenticated
using ((select auth.uid()) = seller_id)
with check ((select auth.uid()) = seller_id);

create policy "Sellers can delete their own listings"
on public.listings for delete to authenticated
using ((select auth.uid()) = seller_id);

create policy "Public can read images of visible listings"
on public.listing_images for select to anon, authenticated
using (
  exists (
    select 1 from public.listings
    where listings.id = listing_images.listing_id
      and listings.status in ('published', 'reserved', 'sold')
  )
);

create policy "Sellers can read images of their own listings"
on public.listing_images for select to authenticated
using (
  exists (
    select 1 from public.listings
    where listings.id = listing_images.listing_id
      and listings.seller_id = (select auth.uid())
  )
);

create policy "Sellers can add images to their own listings"
on public.listing_images for insert to authenticated
with check (
  exists (
    select 1 from public.listings
    where listings.id = listing_images.listing_id
      and listings.seller_id = (select auth.uid())
  )
  and split_part(storage_path, '/', 1) = (select auth.uid()::text)
  and split_part(storage_path, '/', 2) = listing_id::text
);

create policy "Sellers can update images of their own listings"
on public.listing_images for update to authenticated
using (
  exists (
    select 1 from public.listings
    where listings.id = listing_images.listing_id
      and listings.seller_id = (select auth.uid())
  )
)
with check (
  split_part(storage_path, '/', 1) = (select auth.uid()::text)
  and split_part(storage_path, '/', 2) = listing_id::text
);

create policy "Sellers can delete images of their own listings"
on public.listing_images for delete to authenticated
using (
  exists (
    select 1 from public.listings
    where listings.id = listing_images.listing_id
      and listings.seller_id = (select auth.uid())
  )
);

create policy "Users can read only their own favorites"
on public.favorites for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can favorite visible listings"
on public.favorites for insert to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1 from public.listings
    where listings.id = favorites.listing_id
      and listings.status in ('published', 'reserved')
  )
);

create policy "Users can delete only their own favorites"
on public.favorites for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "Public can view completed marketplace profiles"
on public.profiles for select to anon
using (onboarding_completed);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'listing-images',
  'listing-images',
  true,
  6291456,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Owners can read their listing image metadata"
on storage.objects for select to authenticated
using (
  bucket_id = 'listing-images'
  and owner_id = (select auth.uid()::text)
);

create policy "Owners can upload listing images"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'listing-images'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
  and exists (
    select 1 from public.listings
    where listings.id::text = (storage.foldername(name))[2]
      and listings.seller_id = (select auth.uid())
  )
);

create policy "Owners can update their listing images"
on storage.objects for update to authenticated
using (
  bucket_id = 'listing-images'
  and owner_id = (select auth.uid()::text)
)
with check (
  bucket_id = 'listing-images'
  and owner_id = (select auth.uid()::text)
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy "Owners can delete their listing images"
on storage.objects for delete to authenticated
using (
  bucket_id = 'listing-images'
  and owner_id = (select auth.uid()::text)
);

insert into public.categories (slug, label_fr, label_en, symbol, sort_order)
values
  ('telephones', 'Téléphones', 'Phones', 'iphone', 10),
  ('informatique', 'Informatique', 'Computers', 'laptopcomputer', 20),
  ('electronique', 'Électronique', 'Electronics', 'headphones', 30),
  ('mode', 'Mode', 'Fashion', 'tshirt.fill', 40),
  ('maison', 'Maison', 'Home', 'house.fill', 50),
  ('vehicules', 'Véhicules', 'Vehicles', 'car.fill', 60),
  ('beaute', 'Beauté', 'Beauty', 'sparkles', 70),
  ('sports-loisirs', 'Sports & loisirs', 'Sports & leisure', 'figure.run', 80),
  ('bebe-enfant', 'Bébé & enfant', 'Baby & kids', 'figure.2.and.child.holdinghands', 90),
  ('livres', 'Livres', 'Books', 'book.fill', 100),
  ('autres', 'Autres', 'Other', 'shippingbox.fill', 110)
on conflict (slug) do update set
  label_fr = excluded.label_fr,
  label_en = excluded.label_en,
  symbol = excluded.symbol,
  sort_order = excluded.sort_order,
  is_active = true;

comment on table public.listings is 'Marketplace listings. Only owners can mutate; public reads are restricted to visible statuses.';
comment on table public.listing_images is 'Ordered public product image metadata. Storage objects remain owner-scoped for writes.';
comment on table public.favorites is 'Private per-user listing favorites.';
